myapp/app/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myapp/app/rentalgo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('mainapp.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/app/shop/urls.py
# # from django.conf.urls import url
# from django.urls import path
# from . import views
#
# app_name = 'shop'
#
# # urlpatterns = [
# #     url(r'^store', views.product_list, name='product_list'),
# #     url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
# #     url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
# # ]
#
# urlpatterns = [
#     path('store', views.product_list, name='product_list'),
#     path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
#     path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
# ]

myapp/app/shop/models.py
from django import forms
from django.db import models
from django.urls import reverse
from users.models import CustomUser, Profile


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('mainapp:product_list_by_category', args=[self.slug])

RENT_DURATION = (
    ('One Day', 'One Day'),
    ('One Week', 'One Week'),
    ('One Month', 'One Month'),
)
class Product(models.Model):
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    rent_duration = models.CharField(max_length=100, choices=RENT_DURATION)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('mainapp:product_detail', args=[self.id, self.slug])


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'slug', 'category', 'description', 'price', 'rent_duration', 'image']

        name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Product Name', 'class':'form-control'}), required=True)
        slug = forms.SlugField(widget=forms.TextInput(attrs={'placeholder':'Product Slug', 'class':'form-control'}), required=True)
        category = forms.ChoiceField(widget=forms.Select(attrs={"class":"form-control"}), required=True)
        description = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Description", "class":"form-control"}), required=True)
        price = forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control"}), required=True)
        image = forms.ImageField(widget=forms.FileInput(attrs={"class":"form-control"}), required=True)
        rent_duration = forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control'}), choices=RENT_DURATION, required=True)

class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'slug', 'category', 'description', 'price', 'rent_duration', 'image' ]

        name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Product Name', 'class':'form-control'}), required=True)
        slug = forms.SlugField(widget=forms.TextInput(attrs={'placeholder':'Product Slug', 'class':'form-control'}), required=True)
        category = forms.ChoiceField(widget=forms.Select(attrs={"class":"form-control"}), required=True)
        description = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Description", "class":"form-control"}), required=True)
        price = forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control"}), required=True)
        image = forms.ImageField(widget=forms.FileInput(attrs={"class":"form-control"}), required=True)
        rent_duration = forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control'}), choices=RENT_DURATION, required=True)

myapp/app/shop/forms.py
from .models import Product

# from django import forms
# class ProductCreateForm(forms.ModelForm):
#     class Meta:
#         model = Product
#         fields = ['owner', 'name', 'slug', 'category', 'description', 'price', 'image', 'rent_duration']

#         owner = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control", "value":"{{request.user}}", "disabled":"", "readonly":""}), required=True)
#         name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Product Name', 'class':'form-control'}), required=True)
#         slug = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Product Slug', 'class':'form-control'}), required=True)
#         category = forms.MultipleChoiceField(widget=forms.TextInput(attrs={'placeholder':'Product Slug', 'class':'form-control'}), required=True)

myapp/app/shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product
# from cart.forms import CartAddProductForm
# from shop.forms import ProductCreateForm
#
# def product_list(request, category_slug=None):
#     category = None
#     categories = Category.objects.all()
#     products = Product.objects.filter(available=True)
#     if category_slug:
#         category = get_object_or_404(Category, slug=category_slug)
#         products = Product.objects.filter(category=category)
#
#     context = {
#         'category': category,
#         'categories': categories,
#         'products': products
#     }
#     return render(request, 'shop/product/list.html', context)
#
#
# def product_detail(request, id, slug):
#     product = get_object_or_404(Product, id=id, slug=slug, available=True)
#
#     cart_product_form = CartAddProductForm()
#     context = {
#         'product': product,
#         'cart_product_form': cart_product_form
#     }
#     return render(request, 'shop/product/detail.html', context)
#
# def product_create(request):
#     if request.method == 'POST':
#         form = ProductCreateForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#     else:
#         form =  ProductCreateForm()
#     context = {
#         'form':form
#     }
#     return render(request, 'shop/product/create.html', context)

myapp/app/shop/templates/shop/product/create.html
{% extends "shop/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.name|as_crispy_field}}
                {{form.description|as_crispy_field}}
                {{form.price|as_crispy_field}}

            </form>
        </div>
        <div class="col-sm-3"></div>
    </div>
</div>
{% endblock content %}

myapp/app/shop/templates/shop/product/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
{% include "shop/storenavbar.html" %}
<div class="container">
    <br><br><br>
    <div class="row" style="margin-top: 6%">

        <div class="col-sm-10 blog-main">

            <div class="blog-post">
                <div class="row">
                    <div class="card">
                        <div class="card-body">
                            <div class="col-md-6 text-right">
                                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                                    alt="..." style="height: 300px; width: auto">
                            </div>
                            <div class="col-md-6" style="padding-left: 120px">
                                <h3 style="font-size: 40px">{{ product.name }}</h3>
                                <h6>Category:<a href="{{ product.category.get_absolute_url }}">&nbsp;{{ product.category }}</a></h6>
                                <p style="font-size: 30px; font-family: Arial; font-weight:bold">US ${{ product.price }}</p>
                                <br>
                                <p><b>Description</b></p>
                                <p>{{ product.description }}</p>
                                <br>
                                <p class="text-left" style="font: size 12px;font-family:Comic Sans MS">Contact owner: <a href=""><span style="font-size:12px; background: #f7f908;border-radius: 10%; padding: 2px 5px; color: black; font-family: Comic Sans MS">{{product.owner.first_name}} {{product.owner.last_name}}</span> </a></p>
                                <br>
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {% csrf_token %}
                                    
                                    {{ cart_product_form }} 
                                    
                                    <input type="submit" value="add to cart" class="btn btn-primary">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>


            </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->
    </div><!-- /.row -->

    </div><!-- /.container -->
{% endblock %}

myapp/app/shop/templates/shop/product/list.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
{% include 'mainapp/navbar.html' %}

    <div class="hero-wrap hero-bread" style="background-image: url('img/bg_6.jpg');">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Products</span></p>
            <h1 class="mb-0 bread">Collection Products</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section bg-light">
    	<div class="container">
    		<div class="row">
    			<div class="col-md-8 col-lg-10 order-md-last">
    				<div class="row">
              {% for product in products %}
		    			<div class="col-sm-6 col-md-6 col-lg-4 ftco-animate">
		    				<div class="product">
		    					<a href="#" class="img-prod"><img class="img-fluid" src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}">

                  </style>="Colorlib Template">
		    						<span class="status">30%</span>
		    						<div class="overlay"></div>
		    					</a>
		    					<div class="text py-3 px-3">
		    						<h3><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h3>
		    						<div class="d-flex">
		    							<div class="pricing">
				    						<p class="price"><span class="price-sale">US ${{ product.price }}</span></p>
				    					</div>
				    					<div class="rating">
			    							<p class="text-right">
			    								<a href="#"><span class="ion-ios-star-outline"></span></a>
			    								<a href="#"><span class="ion-ios-star-outline"></span></a>
			    								<a href="#"><span class="ion-ios-star-outline"></span></a>
			    								<a href="#"><span class="ion-ios-star-outline"></span></a>
			    								<a href="#"><span class="ion-ios-star-outline"></span></a>
			    							</p>
			    						</div>
			    					</div>
			    					<p class="bottom-area d-flex px-3">
		    							<a href="#" class="add-to-cart text-center py-2 mr-1"><span>Add to cart <i class="ion-ios-add ml-1"></i></span></a>
		    							<a href="#" class="buy-now text-center py-2">Buy now<span><i class="ion-ios-cart ml-1"></i></span></a>
		    						</p>
		    					</div>
		    				</div>
		    			</div>
              {% endfor %}




		    		</div>
		    		<div class="row mt-5">
		          <div class="col text-center">
		            <div class="block-27">
		              <ul>
		                <li><a href="#">&lt;</a></li>
		                <li class="active"><span>1</span></li>
		                <li><a href="#">2</a></li>
		                <li><a href="#">3</a></li>
		                <li><a href="#">4</a></li>
		                <li><a href="#">5</a></li>
		                <li><a href="#">&gt;</a></li>
		              </ul>
		            </div>
		          </div>
		        </div>
		    	</div>

		    	<div class="col-md-4 col-lg-2 sidebar">
		    		<div class="sidebar-box-2">
		    			<h2 class="heading mb-4"><a href="#">Category</a></h2>
		    			<ul>
		    				<li {% if not category %} class="active"{% endif %}><a href="{% url 'mainapp:product_list' %}">All</a></li>
                {% for c in categories %}
								<li {% if category.slug == c.slug %} class="active"{% endif %}>
                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
                {% endfor %}
		    			</ul>
		    		</div>

    			</div>
    		</div>
    	</div>
    </section>
{% endblock content %}