myapp/app/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myapp/app/mainapp/urls.py
from django.urls import path
from . import views
from users import views as userviews

app_name = 'mainapp'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('shop', views.product_list, name='shop'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

    path('product-create', views.product_create, name='product-create'),
    path('product-edit/<int:id>/', views.product_edit, name='product-edit'),
    path('product-delete/<int:id>/', views.product_delete, name='product-delete'),


    path('cart', views.cart_view, name='cart'),
    path('checkout', views.checkout_view, name='checkout'),
    path('contact', views.contact_view, name='contact'),
    path('terms', views.terms_view, name='terms'),

    
    path('your-account', views.youraccount_view, name='your-account'),
    path('first-account-update', userviews.profilefirstupdateview, name='first-account-update'),
    path('account-update', userviews.profileupdateview, name='account-update')
]

myapp/app/orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create')
]

myapp/app/rentalgo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('mainapp.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/app/shop/urls.py
# # from django.conf.urls import url
# from django.urls import path
# from . import views
#
# app_name = 'shop'
#
# # urlpatterns = [
# #     url(r'^store', views.product_list, name='product_list'),
# #     url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
# #     url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
# # ]
#
# urlpatterns = [
#     path('store', views.product_list, name='product_list'),
#     path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
#     path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
# ]

myapp/app/cart/models.py
from django.db import models

# Create your models here.

myapp/app/mainapp/models.py
from django.db import models

# Create your models here.

myapp/app/shop/models.py
from django import forms
from django.db import models
from django.urls import reverse
from users.models import CustomUser, Profile


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('mainapp:product_list_by_category', args=[self.slug])

RENT_DURATION = (
    ('One Day', 'One Day'),
    ('One Week', 'One Week'),
    ('One Month', 'One Month'),
)
class Product(models.Model):
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    rent_duration = models.CharField(max_length=100, choices=RENT_DURATION)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('mainapp:product_detail', args=[self.id, self.slug])


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'slug', 'category', 'description', 'price', 'rent_duration', 'image']

        name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Product Name', 'class':'form-control'}), required=True)
        slug = forms.SlugField(widget=forms.TextInput(attrs={'placeholder':'Product Slug', 'class':'form-control'}), required=True)
        category = forms.ChoiceField(widget=forms.Select(attrs={"class":"form-control"}), required=True)
        description = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Description", "class":"form-control"}), required=True)
        price = forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control"}), required=True)
        image = forms.ImageField(widget=forms.FileInput(attrs={"class":"form-control"}), required=True)
        rent_duration = forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control'}), choices=RENT_DURATION, required=True)

class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'slug', 'category', 'description', 'price', 'rent_duration', 'image' ]

        name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Product Name', 'class':'form-control'}), required=True)
        slug = forms.SlugField(widget=forms.TextInput(attrs={'placeholder':'Product Slug', 'class':'form-control'}), required=True)
        category = forms.ChoiceField(widget=forms.Select(attrs={"class":"form-control"}), required=True)
        description = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Description", "class":"form-control"}), required=True)
        price = forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control"}), required=True)
        image = forms.ImageField(widget=forms.FileInput(attrs={"class":"form-control"}), required=True)
        rent_duration = forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control'}), choices=RENT_DURATION, required=True)

myapp/app/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]

class CartAddProductForm(forms.Form):
    
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myapp/app/shop/forms.py
from .models import Product

# from django import forms
# class ProductCreateForm(forms.ModelForm):
#     class Meta:
#         model = Product
#         fields = ['owner', 'name', 'slug', 'category', 'description', 'price', 'image', 'rent_duration']

#         owner = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control", "value":"{{request.user}}", "disabled":"", "readonly":""}), required=True)
#         name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Product Name', 'class':'form-control'}), required=True)
#         slug = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Product Slug', 'class':'form-control'}), required=True)
#         category = forms.MultipleChoiceField(widget=forms.TextInput(attrs={'placeholder':'Product Slug', 'class':'form-control'}), required=True)

myapp/app/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST 
@login_required
def cart_add(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        # cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
        cart.add(product=product, update_quantity=cd['update'])
    return redirect('cart:cart_detail')

@login_required
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

@login_required
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'mainapp/cart.html', {'cart': cart})

myapp/app/mainapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from shop.models import (Category, 
    Product, ProductCreateForm, ProductEditForm,)



from cart.forms import CartAddProductForm
from django.utils import timezone


def home_view(request):
    items = Product.objects.all().order_by('created_at').reverse()[:4]
    return render(request, 'mainapp/home.html', {'items':items})

def checkout_view(request):
    return render(request, 'mainapp/checkout.html')

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'mainapp/shop.html', context)
# def shop_view(request):
#     return render(request, 'mainapp/shop.html')

def product_detail(request, id, slug):
    related_products = Product.objects.all().order_by('created_at').reverse()[:4]
    product = get_object_or_404(Product, id=id, slug=slug, available=True)

    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form,
        'related_products':related_products
    }
    return render(request, 'mainapp/product-detail.html', context)




@login_required
def product_create(request):
    if request.method == 'POST':
        form = ProductCreateForm(request.POST, request.FILES)
        if form.is_valid():
            befo = form.save(commit=False)
            befo.owner = request.user
            befo.created_at = timezone.now()
            befo.save()
            return redirect('mainapp:your-account')

    else:
        form = ProductCreateForm()
    context = {
        'form':form,
    }
    return render(request, 'mainapp/product-create.html', context)


@login_required
def product_edit(request, id):
    the_product = get_object_or_404(Product, id=id)
    if request.user != the_product.owner:
        return redirect('mainapp:home')

    else:
        if request.method == 'POST':
            form = ProductEditForm(request.POST, request.FILES, instance=the_product)
            if form.is_valid():
                bell = form.save(commit=False)
                bell.owner = request.user
                bell.save()
                return redirect('mainapp:your-account')
        else:
            form = ProductEditForm(instance=the_product)
        context = {
        'form':form
        }

        return render(request, 'mainapp/product-edit.html', context)

@login_required
def product_delete(request, id):
    d_product = get_object_or_404(Product, id=id)
    if request.method == 'POST':
        d_product.delete()
        return redirect('mainapp:your-account')
    context={
    'd_product':d_product
    }
    return render(request, 'mainapp/delete-confirmation.html', context)



def cart_view(request):
    return render(request, 'mainapp/cart.html')

def contact_view(request):
    return render(request, 'mainapp/contact.html')

def terms_view(request):
	return render(request, 'mainapp/terms.html')

@login_required
def youraccount_view(request):
    produ = Product.objects.all()
    pro = produ.filter(owner__username=request.user.username).last()
    your_products = Product.objects.all().filter(owner__username=request.user.username).order_by('-created_at')
    context = {
        'your_products':your_products,
        'pro':pro
    }
    return render(request, 'mainapp/youraccount.html', context)

myapp/app/shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product
# from cart.forms import CartAddProductForm
# from shop.forms import ProductCreateForm
#
# def product_list(request, category_slug=None):
#     category = None
#     categories = Category.objects.all()
#     products = Product.objects.filter(available=True)
#     if category_slug:
#         category = get_object_or_404(Category, slug=category_slug)
#         products = Product.objects.filter(category=category)
#
#     context = {
#         'category': category,
#         'categories': categories,
#         'products': products
#     }
#     return render(request, 'shop/product/list.html', context)
#
#
# def product_detail(request, id, slug):
#     product = get_object_or_404(Product, id=id, slug=slug, available=True)
#
#     cart_product_form = CartAddProductForm()
#     context = {
#         'product': product,
#         'cart_product_form': cart_product_form
#     }
#     return render(request, 'shop/product/detail.html', context)
#
# def product_create(request):
#     if request.method == 'POST':
#         form = ProductCreateForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#     else:
#         form =  ProductCreateForm()
#     context = {
#         'form':form
#     }
#     return render(request, 'shop/product/create.html', context)

myapp/app/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Rentalgo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'css/all.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300&display=swap" rel="stylesheet">
    <script src="{% static 'js/angular.min.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">


    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body class="goto-here">

    {% block content %}
    {% endblock content %}

    <footer class="ftco-footer bg-light ftco-section">
      <div class="container">
      	<div class="row">
      	</div>
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Rentalgo</h2>
              <p>Rent and order stuff at the convinience of your home</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="https:twitter.com/FKemosi"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="https://facebook.com/fredrick.kemosi"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="https://instagram.com/fredricksimi"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-5">
              <h2 class="ftco-heading-2">Menu</h2>
              <ul class="list-unstyled">
                <li><a href="{% url 'mainapp:home' %}" class="py-2 d-block">Home</a></li>
                <li><a href="{% url 'mainapp:shop' %}" class="py-2 d-block">Shop</a></li>
                <li><a href="{% url 'mainapp:contact' %}" class="py-2 d-block">Contact Us</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Help</h2>
              <div class="d-flex">
	              <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
	                <li><a href="{% url 'mainapp:your-account' %}" class="py-2 d-block">Account</a></li>
	                <li><a href="{% url 'mainapp:terms' %}" class="py-2 d-block">Terms of use</a></li>
	              </ul>
	            </div>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">1234 Street.</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+254 7xx xxx xxx</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@rentalgo.abc</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p>
						  Copyright &copy; <script>document.write(new Date().getFullYear());</script> | All rights reserved <br><i class="icon-heart color-danger" aria-hidden="true"></i><br> R E N T A L G O

						</p>
          </div>
        </div>
      </div>
    </footer>




  <script type="text/javascript" src="{% static 'js/prepopulate_init.js' %}" data-prepopulated-fields="[{&quot;id&quot;: &quot;#id_slug&quot;, &quot;name&quot;: &quot;slug&quot;, &quot;dependency_ids&quot;: [&quot;#id_name&quot;], &quot;dependency_list&quot;: [&quot;name&quot;], &quot;maxLength&quot;: 100, &quot;allowUnicode&quot;: false}]">
</script>
  <script type="text/javascript" src="{% static 'js/jquery.init.js' %}"></script>

  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/urlify.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/prepopulate.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/xregexp.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'js/google-map.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>

  </body>
</html>

myapp/app/mainapp/templates/mainapp/delete-confirmation.html
{% extends "mainapp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% include "mainapp/navbar.html" %}
<br><br><br>
<div class="container">
	<div class="row">
		<div class="col-sm-3"></div>

		<div class="col-sm-6">
			<form method="POST">
				{% csrf_token %}
				<h3 class="text-center">Are you sure you want to delete the item <b>{{d_product.name}}</b>?</h3>
				<center><input type="submit" value="Delete" class="btn btn-danger"></center>
			</form><br>
			<center><a href="{% url 'mainapp:your-account' %}"><button class="btn btn-success" style="display: inline;">Cancel</button></a></center>
		</div>

		<div class="col-sm-3"></div>
	</div>
</div>
<br><br>
<br>
{% endblock content %}

myapp/app/mainapp/templates/mainapp/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <a class="navbar-brand" href="{% url 'mainapp:home' %}">Rentalgo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span> Menu
    </button>

    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a href="{% url 'mainapp:home' %}" class="nav-link">Home</a></li>
        <li class="nav-item"><a href="{% url 'mainapp:shop' %}" class="nav-link">Shop</a></li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"><a href="{% url 'mainapp:cart' %}" class="nav-link">Cart <span class="icon-shopping_cart"></span>
          <span style="background-color:#007bff;color:white;padding:2px 2px 2px 3px;border-radius:35%">{% if cart|length > 0 %} {{cart|length}} {% elif cart|length == 0 %} 0{% endif %}</span></a></li>
          {% endif %}
        <li class="nav-item"><a href="{% url 'mainapp:terms' %}" class="nav-link">Terms of use</a></li>
        <li class="nav-item"><a href="{% url 'mainapp:contact' %}" class="nav-link">Contact</a></li>
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle "  id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{request.user.username}}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'mainapp:your-account' %}" style="font-size:10px;letter-spacing:2px;text-transform:uppercase;"><i class="fa fa-user"></i>&nbsp;Your Account</a>
          <a class="dropdown-item" href="{% url 'account_logout' %}" style="font-size:10px;letter-spacing:2px;text-transform:uppercase;"><i class="fa fa-lock"></i>&nbsp;Logout</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item"><a href="{% url 'account_login' %}" class="nav-link"><i class="fa fa-unlock"></i>&nbsp;Login</a></li>
      <li class="nav-item"><a href="{% url 'account_signup' %}" class="nav-link" style="color:#007bff"><i class="fa fa-check" style="color:#007bff"></i>&nbsp;Join us</a></li>
      {% endif %}

      </ul>
    </div>
  </div>
</nav>
<!-- END nav -->

myapp/app/mainapp/templates/mainapp/product-create.html
{% extends "mainapp/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
{% include "mainapp/navbar.html" %}
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" value="Submit">
            </form>
        </div>
        <div class="col-sm-3"></div>
    </div>
</div>

{% endblock content %}

myapp/app/mainapp/templates/mainapp/youraccount.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
{% include 'mainapp/navbar.html' %}
<br><br><br><br><br><br>
<div class="container">
	<div class="row">
		<div class="col-sm-2 ftco-animate"></div>
		<div class="col-sm-3 ftco-animate">
			{% if request.user.is_authenticated %}
			<center>
				{% if not request.user.profile.photo %}
				<i class="fa fa-user-circle"
					style="vertical-align: middle;font-size: 100px;color:black; padding:30px;"></i>
				<p>No photo available</p>
				{% else %}
				<img src="{{request.user.profile.photo.url}}" class="img-fluid img-thumbnail"
					style="border-radius:50%; vertical-align: middle; height: 180px;width: auto;">
				{% endif %}
			</center>
			{% endif %}
		</div>


		<div class="col-sm-3 ftco-animate">
			<p style="font-size: 28px; font-family: 'Source Sans Pro'; color:#262626;">
				{{request.user.profile.first_name}} {{request.user.profile.last_name}}&nbsp;
				{% if pro %}
				<i style="color:#007bff; font-size: 20px;" class="icon-check-circle"></i></p>
				{% endif %} 

			<p><b>Email:</b>{% if request.user.email %} {{request.user.email}} {% else %} None {% endif %}</p>
			<p><b>Postal Address Code:</b>{% if request.user.profile.address and request.user.profile.postal_code %}  {{request.user.profile.address}} - {{request.user.profile.postal_code}} {% else %} None {% endif %}</p>
			<p><b>City:</b>{% if request.user.profile.city %}  {{request.user.profile.city}} {% else %} None {% endif %}</p>
			{% if not request.user.profile %}
			<p style="color:red">Please update your profile</p>
			{% endif %}
		</div>

		<div class="col-sm-2 ftco-animate">
			<center>
				<a
					href="{% if not request.user.profile %} {% url 'mainapp:first-account-update' %} {% else %} {% url 'mainapp:account-update' %} {% endif %}">
					<button class="btn btn-black py-2 px-3">
						<span style="font-size:10px;letter-spacing:2px;text-transform:uppercase;">
							<i class="fa fa-cog"></i>&nbsp;Edit Profile</span>
					</button>
				</a>
			</center>

			<br>

			<center>
				<a href="{% url 'mainapp:product-create' %}">
					<button class="btn btn-black py-2 px-3">
						<span style="font-size:10px;letter-spacing:1px;text-transform:uppercase;">
							<i class="fa fa-paper-plane"></i>&nbsp;Rent Something</span>
					</button>
				</a>
			</center>
		</div>
		<div class="col-sm-2 ftco-animate"></div>
	</div>
	</div>

	
	<div class="container">
		<br><br><br>
		<h2 class="text-center">{% if pro %}Here are the items you are currently renting in our store {% else %} You currently have no items rented out in our store{% endif %}</h2>
		<br><br><br>
	<div class="row">
		
		
		<br><br>
		{% for product in your_products %}
		<div class="col-sm-3 ftco-animate">
			<div class="">
				<a href="{{ product.get_absolute_url }}">
					<center>
						<img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
							alt="..."
							style="height: 200px; width: auto;box-shadow: 0 12px 16px 0 rgba(0,0,0,0.1), 0 17px 50px 0 rgba(0,0,0,0.09);">
					</center>
				</a>
				<div class="caption"><br>
					<p class="text-center">
						<a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
					</p>
					<p class="text-center" style="margin-top:-10px">US ${{ product.price }}<br>
						<a href="{% url 'mainapp:product-edit' product.id %}"><button class="btn btn-success py-1 px-2"><i style="font-size: 10px;" class="fa fa-pen"></i>&nbsp;
							<span style="font-size:10px;text-transform:uppercase;letter-spacing:2px;">Edit</span></button></a>

						<a href="{% url 'mainapp:product-delete' product.id %}"><button class="btn btn-danger py-1 px-2"><i
									class="fa fa-trash-alt" style="font-size: 10px;"></i>&nbsp;
									<span style="font-size:10px;text-transform:uppercase;letter-spacing:2px;">Delete</span></button></a>
					</p>
				</div><br><br>
			</div>
		</div>
		{% endfor %}
	</div>
</div>


{% endblock content %}