myapp/app/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myapp/app/mainapp/urls.py
from django.urls import path
from . import views
from users import views as userviews

app_name = 'mainapp'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('shop', views.product_list, name='shop'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

    path('product-create', views.product_create, name='product-create'),
    path('product-edit/<int:id>/', views.product_edit, name='product-edit'),
    path('product-delete/<int:id>/', views.product_delete, name='product-delete'),


    path('cart', views.cart_view, name='cart'),
    path('checkout', views.checkout_view, name='checkout'),
    path('contact', views.contact_view, name='contact'),
    path('terms', views.terms_view, name='terms'),

    
    path('your-account', views.youraccount_view, name='your-account'),
    path('first-account-update', userviews.profilefirstupdateview, name='first-account-update'),
    path('account-update', userviews.profileupdateview, name='account-update')
]

myapp/app/orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create')
]

myapp/app/rentalgo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('mainapp.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/app/cart/models.py
from django.db import models

# Create your models here.

myapp/app/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]

class CartAddProductForm(forms.Form):
    
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myapp/app/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST 
@login_required
def cart_add(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        # cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
        cart.add(product=product, update_quantity=cd['update'])
    return redirect('cart:cart_detail')

@login_required
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

@login_required
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'mainapp/cart.html', {'cart': cart})

myapp/app/cart/templates/cart/detail.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
{% include "mainapp/navbar.html" %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url 'cart:cart_detail' %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }}, US ${{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
        {% if cart|length > 0 %}
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <!-- <th>Quantity</th> -->
                        <!-- <th>Unit Price</th> -->
                        <th>Price</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>

                            <td>{{ product.name }}</td>
                            <td>US ${{ item.total_price }}</td>
                            <td>
                                <a href="{% url 'cart:cart_remove' product.id %}">Remove</a>
                            </td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="2"></td>
                    <td colspan="num"><b>US ${{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
            {% else %}
            <p class="text-muted text-center">You have no items in your cart. Please shop something</p>
            {% endif %}
        <p class="text-right">
            {% if cart|length > 0 %}
            <a href="{% url 'mainapp:shop' %}" class="btn btn-default">Continue Shopping</a>
            <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Checkout</a>
            {% else %}
            <!-- <a href="{% url "mainapp:shop" %}" class="btn btn-default" disabled>Continue Shopping</a>
            <a href="{% url "orders:order_create" %}" class="btn btn-primary" disabled>Checkout</a>                          -->
            {% endif %}

        </p>
        </div>
    </div>
{% endblock %}